import type { Country } from '@/types/youtube';

export const COUNTRIES: Country[] = [
  { code: 'KR', name: '한국', flag: '🇰🇷' },
  { code: 'US', name: '미국', flag: '🇺🇸' },
  { code: 'JP', name: '일본', flag: '🇯🇵' },
  { code: 'GB', name: '영국', flag: '🇬🇧' },
  { code: 'DE', name: '독일', flag: '🇩🇪' },
  { code: 'FR', name: '프랑스', flag: '🇫🇷' },
  { code: 'CA', name: '캐나다', flag: '🇨🇦' },
  { code: 'AU', name: '호주', flag: '🇦🇺' },
  { code: 'IN', name: '인도', flag: '🇮🇳' },
  { code: 'BR', name: '브라질', flag: '🇧🇷' },
  { code: 'MX', name: '멕시코', flag: '🇲🇽' },
  { code: 'IT', name: '이탈리아', flag: '🇮🇹' },
  { code: 'ES', name: '스페인', flag: '🇪🇸' },
  { code: 'RU', name: '러시아', flag: '🇷🇺' },
  { code: 'TW', name: '대만', flag: '🇹🇼' },
  { code: 'TH', name: '태국', flag: '🇹🇭' },
  { code: 'VN', name: '베트남', flag: '🇻🇳' },
  { code: 'ID', name: '인도네시아', flag: '🇮🇩' },
  { code: 'SG', name: '싱가포르', flag: '🇸🇬' },
  { code: 'PH', name: '필리핀', flag: '🇵🇭' },
  { code: 'MY', name: '말레이시아', flag: '🇲🇾' },
  { code: 'AR', name: '아르헨티나', flag: '🇦🇷' },
  { code: 'NG', name: '나이지리아', flag: '🇳🇬' },
  { code: 'ZA', name: '남아프리카', flag: '🇿🇦' },
  { code: 'EG', name: '이집트', flag: '🇪🇬' },
  { code: 'PL', name: '폴란드', flag: '🇵🇱' },
  { code: 'NL', name: '네덜란드', flag: '🇳🇱' },
  { code: 'SE', name: '스웨덴', flag: '🇸🇪' },
  { code: 'NO', name: '노르웨이', flag: '🇳🇴' },
  { code: 'DK', name: '덴마크', flag: '🇩🇰' },
];

export const EDUCATION_CATEGORY_ID = '27';

export const DEFAULT_CATEGORIES = [
  { id: '0', title: '전체' },
  { id: '1', title: '영화/애니메이션' },
  { id: '2', title: '자동차/차량' },
  { id: '10', title: '음악' },
  { id: '15', title: '반려동물/동물' },
  { id: '17', title: '스포츠' },
  { id: '19', title: '여행/이벤트' },
  { id: '20', title: '게임' },
  { id: '22', title: '인물/블로그' },
  { id: '23', title: '코미디' },
  { id: '24', title: '엔터테인먼트' },
  { id: '25', title: '뉴스/정치' },
  { id: '26', title: '노하우/스타일' },
  { id: '27', title: '교육' },
  { id: '28', title: '과학/기술' },
  { id: '29', title: '비영리/사회운동' },
];
